In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('homicidios_limpio.csv', sep=';')

In [8]:
df.columns

Index(['id_hecho', 'provincia_id', 'provincia_nombre', 'localidad_id',
       'localidad_nombre', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado',
       'motivo_origen_registro', 'motivo_origen_registro_otro', 'victima_sexo',
       'victima_identidad_genero', 'victima_identidad_genero_otro',
       'victima_tr_edad', 'victima_18_anios_o_mas', 'inculpado_sexo',
       'inculpado_identidad_genero', 'inculpado_identidad_genero_otro',
       'inculpado_tr_edad', 'inculpado_18_anios_o_mas'],
      dtype='object')

In [18]:
provincia_nombre = df['provincia_nombre'].unique()

In [19]:
provincia_nombre

array(['Neuquén', 'Salta', 'Chubut', 'Catamarca', 'Santa Fe',
       'Tierra del Fuego', 'Santa Cruz', 'San Juan', 'Tucumán', 'Formosa',
       'La Pampa', 'Misiones', 'Corrientes', 'Mendoza', 'San Luis',
       'Jujuy', 'Río Negro', 'Santiago del Estero', 'La Rioja', 'Chaco',
       'Entre Ríos', 'Córdoba', 'Ciudad Autónoma de Buenos Aires',
       'Buenos Aires'], dtype=object)

In [21]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
df_censo = pd.read_excel('c2022_tp_c_resumen.xlsx', skiprows=4, header=None)

In [29]:
# Como le dijimos header=None, las columnas se llamarán con números (0, 1, 2...). 
# Por Excel, sabemos que:
# Columna 0 = Jurisdicción (Provincia)
# Columna 1 = Total de población

df_censo = df_censo.iloc[:, [0, 1]] # Nos quedamos solo con esas dos columnas
df_censo.columns = ['provincia_nombre', 'poblacion'] # Les ponemos nombre claro

In [30]:
# Limpiamos posibles filas vacías al final o al principio
df_censo = df_censo.dropna(subset=['provincia_nombre'])

In [31]:
df_censo.head()

                  provincia_nombre   poblacion
0                   Total del país  45892285.0
1  Ciudad Autónoma de Buenos Aires   3121707.0
2                     Buenos Aires  17523996.0
3                        Catamarca    429562.0
4                            Chaco   1129606.0

In [32]:
df_censo['provincia_nombre'].unique()

array(['Total del país', 'Ciudad Autónoma de Buenos Aires',
       'Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba',
       'Corrientes', 'Entre Ríos', 'Formosa', 'Jujuy', 'La Pampa',
       'La Rioja', 'Mendoza', 'Misiones', 'Neuquén', 'Rio Negro', 'Salta',
       'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fe',
       'Santiago del Estero',
       'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Tucumán',
       '(¹) Excluye la población censada en refugios o paradores.',
       '(²) Incluye la población en situación de calle censada en refugios o paradores.',
       'Nota: de acuerdo con la evaluación de calidad y consistencia de los resultados definitivos, y para cumplir con los estándares de calidad estadística requeridos por el INDEC, la categoría X de las respuestas a la pregunta por sexo registrado al nacer se redistribuye entre las categorías Mujer/Femenino y Varón/Masculino.',
       'Fuente: INDEC, Censo Nacional de Población, Hogares y Viviendas 2022. Resultados definitivos.'],
      dtype=object)

In [35]:
provincia_nombre

array(['Neuquén', 'Salta', 'Chubut', 'Catamarca', 'Santa Fe',
       'Tierra del Fuego', 'Santa Cruz', 'San Juan', 'Tucumán', 'Formosa',
       'La Pampa', 'Misiones', 'Corrientes', 'Mendoza', 'San Luis',
       'Jujuy', 'Río Negro', 'Santiago del Estero', 'La Rioja', 'Chaco',
       'Entre Ríos', 'Córdoba', 'Ciudad Autónoma de Buenos Aires',
       'Buenos Aires'], dtype=object)

In [ ]:
#  Nos quedamos solo con las filas de las 24 jurisdicciones (excluimos notas y totales)
df_censo = df_censo.iloc[1:25].copy()

# Reemplazamos el nombre de Tierra del Fuego para que coincida exactamente con tu base
df_censo['provincia_nombre'] = df_censo['provincia_nombre'].replace({
    'Tierra del Fuego, Antártida e Islas del Atlántico Sur': 'Tierra del Fuego'
})

In [37]:
df_censo['poblacion'].unique()

array([ 3121707., 17523996.,   429562.,  1129606.,   592621.,  3840905.,
        1212696.,  1425578.,   607419.,   811611.,   361859.,   383865.,
        2043540.,  1278873.,   710814.,   750768.,  1441351.,   822853.,
         542069.,   337226.,  3544908.,  1060906.,   185732.,  1731820.])

In [38]:
df_censo.head()

                  provincia_nombre   poblacion
1  Ciudad Autónoma de Buenos Aires   3121707.0
2                     Buenos Aires  17523996.0
3                        Catamarca    429562.0
4                            Chaco   1129606.0
5                           Chubut    592621.0

In [39]:
df_censo.to_excel('censo_limpio.xlsx', index=False)