In [3]:
import pandas as pd

In [4]:
# cargar el archivo limpio
df = pd.read_csv('homicidios_limpio.csv', sep=';')

In [5]:
df.columns

Index(['id_hecho', 'provincia_id', 'provincia_nombre', 'localidad_id',
       'localidad_nombre', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado',
       'motivo_origen_registro', 'motivo_origen_registro_otro', 'victima_sexo',
       'victima_identidad_genero', 'victima_identidad_genero_otro',
       'victima_tr_edad', 'victima_18_anios_o_mas', 'inculpado_sexo',
       'inculpado_identidad_genero', 'inculpado_identidad_genero_otro',
       'inculpado_tr_edad', 'inculpado_18_anios_o_mas'],
      dtype='object')

In [6]:
# Tabla PROVINCIA
df_provincia = df[['provincia_id', 'provincia_nombre']].drop_duplicates().reset_index(drop=True)

In [7]:
df_provincia.head()

   provincia_id provincia_nombre
0            58          Neuquén
1            66            Salta
2            26           Chubut
3            10        Catamarca
4            82         Santa Fe

In [8]:
# Tabla LOCALIDAD
df_localidad = df[['localidad_id','localidad_nombre']].drop_duplicates().reset_index(drop=True)

In [9]:
df_localidad.head()

   localidad_id localidad_nombre
0         100.0         Plottier
1          40.0        Cutral Có
2          70.0          Neuquén
3          10.0        Barrancas
4          30.0       Las Ovejas

In [10]:
# Tabla HECHO
df_hecho = df[['id_hecho', 'localidad_id', 'anio', 'mes',
 'fecha_hecho', 'hora_hecho', 'tipo_lugar', 'tipo_lugar_otro',
  'tipo_lugar_ampliado', 'motivo_origen_registro',
   'motivo_origen_registro_otro']].drop_duplicates().reset_index(drop=True)

In [11]:
df_hecho.head()

,id_hecho,localidad_id,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,tipo_lugar_otro,tipo_lugar_ampliado,motivo_origen_registro,motivo_origen_registro_otro
0,11535,100.0,2017,1,2017-01-14,22:38:00,Domicilio particular,No especificado,Domicilio particular,Intervención policial,No especificado
1,11536,40.0,2017,1,2017-01-07,10:35:00,Vía pública,No especificado,Vía pública,Intervención policial,No especificado
2,11537,70.0,2017,1,2017-01-07,16:38:00,Vía pública,No especificado,Vía pública,Intervención policial,No especificado
3,11538,10.0,2017,1,2017-01-02,22:00:00,Domicilio particular,No especificado,Domicilio particular,Intervención policial,No especificado
4,11539,70.0,2017,4,2017-04-03,23:55:00,Vía pública,No especificado,Vía pública,Intervención policial,No especificado

In [12]:
# Tabla INVOLUCRADOS
columnas_involucrados = ['id_hecho',
'victima_sexo',
'victima_identidad_genero',
'victima_identidad_genero_otro',
'victima_tr_edad',
'victima_18_anios_o_mas',
'inculpado_sexo',
'inculpado_identidad_genero',
'inculpado_identidad_genero_otro',
'inculpado_tr_edad',
'inculpado_18_anios_o_mas']

df_involucrados = df[columnas_involucrados].drop_duplicates().reset_index(drop=True)

In [13]:
df_involucrados.head()

,id_hecho,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_anios_o_mas
0,11535,Masculino,Varón,No especificado,45-49,Si,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar
1,11535,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
2,11536,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,Masculino,Varón,No especificado,20-24,Si
3,11536,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,Masculino,Varón,No especificado,30-34,Si
4,11536,Masculino,Varón,No especificado,40-44,Si,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar

In [16]:
print(df_localidad.columns)

Index(['localidad_id', 'localidad_nombre'], dtype='object')

In [17]:
#  Tabla Localidad (pasar a enteros)
df_localidad['localidad_id'] = df_localidad['localidad_id'].astype('Int64')

In [ ]:
print(df_hecho.colu)

Index(['id_hecho', 'localidad_id', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado',
       'motivo_origen_registro', 'motivo_origen_registro_otro'],
      dtype='object')

In [ ]:
# Tabla Hecho
df_hecho['localidad_id'] = df_hecho['localidad_id'].astype('Int64')
df_hecho['anio'] = df_hecho['anio'].astype('Int64')
df_hecho['mes'] = df_hecho['mes'].astype('Int64')

In [21]:
df_provincia.columns

Index(['provincia_id', 'provincia_nombre'], dtype='object')

In [ ]:
# Tabla Provincia
df_provincia['provincia_id'] = df_provincia['provincia_id'].astype('Int64')

In [24]:
# Exportamos las tablas
df_provincia.to_csv('provincia.csv', index=False, encoding='utf-8')
df_localidad.to_csv('localidad.csv', index=False, encoding='utf-8')
df_hecho.to_csv('hecho.csv', index=False, encoding='utf-8')
#df_involucrados.to_csv('involucrados.csv', index=False, encoding='utf-8')

In [25]:
df_localidad.to_csv('localidad.csv', index=False, encoding='utf-8', float_format='%.0f')
df_hecho.to_csv('hecho.csv', index=False, encoding='utf-8', float_format='%.0f')

In [26]:
# Reemplaza los nulos en localidad_id por un número (ej: 0) antes de exportar
df_localidad['localidad_id'] = df_localidad['localidad_id'].fillna(0).astype('Int64')

# Vuelvo a exportar el CSV limpio
df_localidad.to_csv('localidad.csv', index=False, encoding='utf-8', float_format='%.0f')

In [27]:
# Eliminar filas con localidad_id repetido
df_localidad.drop_duplicates(subset=['localidad_id'], inplace=True)

# Volver a exportar el CSV limpio
df_localidad.to_csv('localidad.csv', index=False, encoding='utf-8', float_format='%.0f')

In [29]:
df_hecho.columns

Index(['id_hecho', 'localidad_id', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado',
       'motivo_origen_registro', 'motivo_origen_registro_otro'],
      dtype='object')

In [30]:
# 1. Renombrar la columna
df_hecho.rename(columns={'id_hecho': 'hecho_id'}, inplace=True)

# 2. Eliminar duplicados (ahora usando el nombre correcto)
df_hecho.drop_duplicates(subset=['hecho_id'], inplace=True)

# 3. Exportar el CSV limpio
df_hecho.to_csv('hecho.csv', index=False, encoding='utf-8', float_format='%.0f')