In [44]:
import pandas as pd

In [45]:
df = pd.read_csv('C:\\PROYECTOS\\SQL\\homicidios\\data\\homicidios_limpio.csv', sep=';')

In [46]:
df.columns

Index(['id_hecho', 'tipo_persona_id', 'provincia_id', 'provincia_nombre',
       'departamento_id', 'departamento_nombre', 'localidad_id',
       'localidad_nombre', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado',
       'motivo_origen_registro', 'motivo_origen_registro_otro', 'victima_sexo',
       'victima_identidad_genero', 'victima_identidad_genero_otro',
       'victima_tr_edad', 'victima_18_anios_o_mas',
       'victima_relacion_inculpado', 'inculpado_sexo',
       'inculpado_identidad_genero', 'inculpado_identidad_genero_otro',
       'inculpado_tr_edad', 'inculpado_18_anios_o_mas', 'categoria_femicidio'],
      dtype='object')

In [47]:
provincia_nombre = df['provincia_nombre'].unique()

In [48]:
provincia_nombre

array(['Neuquén', 'Salta', 'Chubut', 'Catamarca', 'Santa Fe',
       'Tierra del Fuego', 'Santa Cruz', 'San Juan', 'Tucuman', 'Formosa',
       'La Pampa', 'Misiones', 'Corrientes', 'Mendoza', 'San Luis',
       'Jujuy', 'Rio Negro', 'Santiago del Estero', 'La Rioja', 'Chaco',
       'Entre Ríos', 'Cordoba', 'Ciudad Autonoma de Buenos Aires',
       'Buenos Aires'], dtype=object)

In [49]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\germa\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\germa\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
df_censo = pd.read_excel('C:\\PROYECTOS\\SQL\\homicidios\\data\\c2022_tp_c_resumen.xlsx', skiprows=4, header=None)

In [51]:
# Como le dijimos header=None, las columnas se llamarán con números (0, 1, 2...). 
# Por Excel, sabemos que:
# Columna 0 = Jurisdicción (Provincia)
# Columna 1 = Total de población

df_censo = df_censo.iloc[:, [0, 1]] # Nos quedamos solo con esas dos columnas
df_censo.columns = ['provincia_nombre', 'poblacion'] # Les ponemos nombre claro

In [52]:
# Limpiamos posibles filas vacías al final o al principio
df_censo = df_censo.dropna(subset=['provincia_nombre'])

In [53]:
df_censo.head()

                  provincia_nombre   poblacion
0                   Total del país  45892285.0
1  Ciudad Autónoma de Buenos Aires   3121707.0
2                     Buenos Aires  17523996.0
3                        Catamarca    429562.0
4                            Chaco   1129606.0

In [54]:
df_censo['provincia_nombre'].unique()

array(['Total del país', 'Ciudad Autónoma de Buenos Aires',
       'Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba',
       'Corrientes', 'Entre Ríos', 'Formosa', 'Jujuy', 'La Pampa',
       'La Rioja', 'Mendoza', 'Misiones', 'Neuquén', 'Rio Negro', 'Salta',
       'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fe',
       'Santiago del Estero',
       'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Tucumán',
       '(¹) Excluye la población censada en refugios o paradores.',
       '(²) Incluye la población en situación de calle censada en refugios o paradores.',
       'Nota: de acuerdo con la evaluación de calidad y consistencia de los resultados definitivos, y para cumplir con los estándares de calidad estadística requeridos por el INDEC, la categoría X de las respuestas a la pregunta por sexo registrado al nacer se redistribuye entre las categorías Mujer/Femenino y Varón/Masculino.',
       'Fuente: INDEC, Censo Nacional de Población, Hogares y Viviendas 2022. Resultados definitivos.'],
      dtype=object)

In [55]:
provincia_nombre

array(['Neuquén', 'Salta', 'Chubut', 'Catamarca', 'Santa Fe',
       'Tierra del Fuego', 'Santa Cruz', 'San Juan', 'Tucuman', 'Formosa',
       'La Pampa', 'Misiones', 'Corrientes', 'Mendoza', 'San Luis',
       'Jujuy', 'Rio Negro', 'Santiago del Estero', 'La Rioja', 'Chaco',
       'Entre Ríos', 'Cordoba', 'Ciudad Autonoma de Buenos Aires',
       'Buenos Aires'], dtype=object)

In [56]:
#  Nos quedamos solo con las filas de las 24 jurisdicciones (excluimos notas y totales)
df_censo = df_censo.iloc[1:25].copy()

# Estandarizar los nombres de las provincias
df_censo['provincia_nombre'] = df_censo['provincia_nombre'].replace({
    'Tierra del Fuego, Antártida e Islas del Atlántico Sur': 'Tierra del Fuego',
    'Ciudad Autónoma de Buenos Aires': 'Ciudad Autonoma de Buenos Aires',
    'Córdoba': 'Cordoba',
    'Tucumán': 'Tucuman'
})

In [57]:
df_censo['poblacion'].unique()

array([ 3121707., 17523996.,   429562.,  1129606.,   592621.,  3840905.,
        1212696.,  1425578.,   607419.,   811611.,   361859.,   383865.,
        2043540.,  1278873.,   710814.,   750768.,  1441351.,   822853.,
         542069.,   337226.,  3544908.,  1060906.,   185732.,  1731820.])

In [58]:
df_censo.head()

                  provincia_nombre   poblacion
1  Ciudad Autonoma de Buenos Aires   3121707.0
2                     Buenos Aires  17523996.0
3                        Catamarca    429562.0
4                            Chaco   1129606.0
5                           Chubut    592621.0

In [59]:
df_censo.to_excel(r'C:\PROYECTOS\SQL\homicidios\data\censo_limpio.xlsx', index=False)